#!/bin/sh
# Regenerate THIRD_PARTY_NOTICES.md from the modules compiled into the Kobo
# agent (read from the built binary) plus the bundled NickelMenu.
#
# Usage: make kobo && scripts/third-party-notices.sh
set -eu
cd "$(dirname "$0")/.."
bin=build/root/usr/local/ezkobo/ezkobo
nm_license=.cache/NickelMenu-LICENSE
ndb_license=.cache/NickelDBus-LICENSE
[ -f "$bin" ] || { echo "Build first: make kobo" >&2; exit 1; }
[ -f "$nm_license" ] || gh api repos/pgaskin/NickelMenu/license --jq .content | base64 -d > "$nm_license"
[ -f "$ndb_license" ] || gh api repos/shermp/NickelDBus/license --jq .content | base64 -d > "$ndb_license"
modcache=$(go env GOMODCACHE)

{
	echo "# Third-party notices"
	echo
	echo "EzKobo's own code is MIT-licensed (see \`LICENSE\`). The Kobo agent includes"
	echo "the Go modules below. The Kobo packages also bundle NickelDBus, and"
	echo "\`KoboRoot-with-NickelMenu.tgz\` NickelMenu. Their licenses follow. (Generated by"
	echo "\`scripts/third-party-notices.sh\`.)"
	echo
	echo "## NickelMenu — https://github.com/pgaskin/NickelMenu"
	echo
	echo '````'
	cat "$nm_license"
	echo
	echo '````'
	echo
	echo "## NickelDBus — https://github.com/shermp/NickelDBus"
	echo
	echo '````'
	cat "$ndb_license"
	echo
	echo '````'
	go version -m "$bin" | awk '$1 == "dep" { print $2, $3 }' | while read -r mod ver; do
		# The module cache escapes capital letters as !lowercase.
		dir="$modcache/$(echo "$mod" | sed -E 's/([A-Z])/!\L\1/g')@$ver"
		echo
		echo "## $mod $ver"
		find "$dir" -maxdepth 4 -type f \( -iname 'LICEN[CS]E*' -o -iname 'COPYING*' \) | sort | while read -r f; do
			echo
			echo "\`${f#"$dir"/}\`"
			echo
			echo '````'
			cat "$f"
			echo
			echo '````'
		done
	done
} > THIRD_PARTY_NOTICES.md
echo "Wrote THIRD_PARTY_NOTICES.md"
